ARCHITECTURE_STYLES = [
    {
        "id": "ancient_egyptian",
        "name": "Staroegipatska arhitektura",
        "period": "oko 3000. pr. Kr. - 30. pr. Kr.",
        "regions": ["Egipat", "Nubija"],
        "materials": ["kamen", "vapnenac", "granit", "opeka od blata"],
        "features": ["masivni kameni blokovi", "pilon vrata", "stupovi s kapitelima", "hijeroglifi", "simetrija"],
        "prompt": "ancient Egyptian monumental architecture, massive stone pylons, carved columns, hieroglyphic reliefs, temple facade",
    },
    {
        "id": "classical_greek",
        "name": "Klasična grčka arhitektura",
        "period": "oko 700. pr. Kr. - 146. pr. Kr.",
        "regions": ["Grčka", "Mediteran"],
        "materials": ["mramor", "vapnenac", "kamen"],
        "features": ["dorski stupovi", "jonski stupovi", "korintski stupovi", "trokutasti zabat", "hram", "proporcije"],
        "prompt": "classical Greek temple architecture, marble columns, triangular pediment, entablature, balanced proportions",
    },
    {
        "id": "roman",
        "name": "Rimska arhitektura",
        "period": "oko 500. pr. Kr. - 476.",
        "regions": ["Italija", "Rimsko Carstvo"],
        "materials": ["beton", "kamen", "opeka", "mramor"],
        "features": ["lukovi", "svodovi", "kupole", "amfiteatar", "akvadukt", "monumentalnost"],
        "prompt": "ancient Roman architecture, round arches, vaults, concrete structure, amphitheater, monumental stone facade",
    },
    {
        "id": "byzantine",
        "name": "Bizantska arhitektura",
        "period": "330. - 1453.",
        "regions": ["Bizant", "Balkan", "Mala Azija", "Istočni Mediteran"],
        "materials": ["opeka", "kamen", "mozaik", "mramor"],
        "features": ["velika kupola", "polukupole", "mozaici", "centralni tlocrt", "okrugli lukovi"],
        "prompt": "Byzantine church architecture, central dome, brick and stone walls, arches, mosaics, sacred interior",
    },
    {
        "id": "islamic",
        "name": "Islamska arhitektura",
        "period": "7. stoljeće - danas",
        "regions": ["Bliski istok", "Sjeverna Afrika", "Španjolska", "Perzija", "Osmansko Carstvo"],
        "materials": ["kamen", "opeka", "pločice", "stuko", "mramor"],
        "features": ["džamija", "minareti", "kupole", "potkovičasti luk", "arabeske", "geometrijski ornamenti", "unutarnje dvorište"],
        "prompt": "Islamic architecture, minarets, domes, horseshoe arches, geometric tile patterns, ornate courtyard",
    },
    {
        "id": "romanesque",
        "name": "Romanika",
        "period": "10. - 12. stoljeće",
        "regions": ["Zapadna Europa"],
        "materials": ["kamen", "debeli zidovi", "drvo"],
        "features": ["polukružni lukovi", "debeli zidovi", "mali prozori", "teški tornjevi", "bazilika"],
        "prompt": "Romanesque architecture, thick stone walls, rounded arches, small windows, heavy church tower",
    },
    {
        "id": "gothic",
        "name": "Gotika",
        "period": "12. - 16. stoljeće",
        "regions": ["Francuska", "Engleska", "Njemačka", "Europa"],
        "materials": ["kamen", "vitraj", "olovo"],
        "features": ["siljasti lukovi", "rebrasti svod", "leteći kontrafori", "visoki tornjevi", "vitraji", "rozeta"],
        "prompt": "Gothic cathedral architecture, pointed arches, flying buttresses, ribbed vaults, stained glass rose window, tall spires",
    },
    {
        "id": "renaissance",
        "name": "Renesansa",
        "period": "15. - 16. stoljeće",
        "regions": ["Italija", "Europa"],
        "materials": ["kamen", "mramor", "zidana konstrukcija"],
        "features": ["simetrija", "kupola", "pilastri", "klasični redovi", "harmonične proporcije", "rustika"],
        "prompt": "Renaissance architecture, symmetrical facade, classical columns, pilasters, dome, harmonious proportions",
    },
    {
        "id": "baroque",
        "name": "Barok",
        "period": "17. - sredina 18. stoljeća",
        "regions": ["Italija", "Francuska", "Austrija", "Srednja Europa"],
        "materials": ["kamen", "stuko", "mramor", "pozlata"],
        "features": ["dramatična fasada", "krivulje", "bogata dekoracija", "ovalni prostori", "dinamika", "kupole"],
        "prompt": "Baroque architecture, dramatic curved facade, ornate decoration, sculptural details, grand church, dynamic composition",
    },
    {
        "id": "rococo",
        "name": "Rokoko",
        "period": "18. stoljeće",
        "regions": ["Francuska", "Njemačka", "Austrija"],
        "materials": ["stuko", "pozlata", "pastelne boje", "mramor"],
        "features": ["asimetrični ornamenti", "pastelni interijeri", "lagana dekoracija", "školjkasti motivi", "elegancija"],
        "prompt": "Rococo architecture, light ornate decoration, shell motifs, pastel colors, gilded stucco, elegant palace interior",
    },
    {
        "id": "neoclassical",
        "name": "Neoklasicizam",
        "period": "sredina 18. - 19. stoljeće",
        "regions": ["Europa", "SAD"],
        "materials": ["kamen", "mramor", "zidana fasada"],
        "features": ["kolonada", "trokutasti zabat", "stroga simetrija", "klasični hram", "čista fasada"],
        "prompt": "Neoclassical architecture, grand columns, triangular pediment, symmetrical stone facade, classical temple front",
    },
    {
        "id": "palladian",
        "name": "Paladijanizam",
        "period": "16. - 18. stoljeće",
        "regions": ["Italija", "Engleska", "Europa"],
        "materials": ["kamen", "zidana konstrukcija", "mramor"],
        "features": ["centralni portik", "simetrija", "klasični stupovi", "vila", "paladijanski prozor"],
        "prompt": "Palladian villa architecture, symmetrical facade, central portico, classical columns, Palladian window",
    },
    {
        "id": "victorian",
        "name": "Viktorijanska arhitektura",
        "period": "1837. - 1901.",
        "regions": ["Velika Britanija", "SAD", "Commonwealth"],
        "materials": ["opeka", "drvo", "kamen", "željezo"],
        "features": ["strmi krovovi", "ukrasni zabati", "erkeri", "bogata fasada", "asimetrija", "verande"],
        "prompt": "Victorian architecture, ornate house facade, steep roofs, bay windows, decorative gables, asymmetrical composition",
    },
    {
        "id": "gothic_revival",
        "name": "Neogotika",
        "period": "18. - 19. stoljeće",
        "regions": ["Europa", "SAD"],
        "materials": ["kamen", "opeka", "vitraj"],
        "features": ["siljasti lukovi", "dekorativni tornjici", "vitraji", "historicistička fasada", "vertikalnost"],
        "prompt": "Gothic Revival architecture, pointed arches, decorative pinnacles, stained glass, historicist facade, vertical emphasis",
    },
    {
        "id": "art_nouveau",
        "name": "Secesija / Art Nouveau",
        "period": "1890. - 1914.",
        "regions": ["Europa", "Belgija", "Francuska", "Austrija", "Mađarska"],
        "materials": ["željezo", "staklo", "keramika", "kamen", "stuko"],
        "features": ["valovite linije", "biljni ornamenti", "kovano željezo", "dekorativna fasada", "organski motivi"],
        "prompt": "Art Nouveau architecture, flowing organic lines, floral ornaments, decorative ironwork, curved facade, ceramic details",
    },
    {
        "id": "art_deco",
        "name": "Art Deco",
        "period": "1920-e - 1930-e",
        "regions": ["SAD", "Francuska", "Europa"],
        "materials": ["beton", "kamen", "metal", "staklo", "terakota"],
        "features": ["geometrijski ornamenti", "stepenaste forme", "vertikalne linije", "zigzag motivi", "luksuzni detalji"],
        "prompt": "Art Deco architecture, geometric ornament, stepped facade, vertical lines, zigzag patterns, elegant modern building",
    },
    {
        "id": "bauhaus",
        "name": "Bauhaus",
        "period": "1919. - 1933.",
        "regions": ["Njemačka", "Europa"],
        "materials": ["beton", "staklo", "čelik", "zidana konstrukcija"],
        "features": ["ravni krov", "bijele plohe", "funkcionalnost", "horizontalni prozori", "minimalna dekoracija"],
        "prompt": "Bauhaus architecture, white geometric volumes, flat roof, horizontal windows, functional modernist design",
    },
    {
        "id": "modernism",
        "name": "Modernizam",
        "period": "1920-e - 1970-e",
        "regions": ["Europa", "SAD", "svijet"],
        "materials": ["armirani beton", "staklo", "čelik"],
        "features": ["ravni krov", "otvoreni tlocrt", "bez ornamenta", "velike staklene površine", "čiste linije"],
        "prompt": "Modernist architecture, clean lines, flat roof, glass and concrete, minimal ornament, functional building",
    },
    {
        "id": "international_style",
        "name": "Internacionalni stil",
        "period": "1930-e - 1970-e",
        "regions": ["SAD", "Europa", "svijet"],
        "materials": ["čelik", "staklo", "beton"],
        "features": ["staklena fasada", "pravokutni volumen", "mrežasta struktura", "bez dekoracije", "uredska zgrada"],
        "prompt": "International Style architecture, glass curtain wall, steel frame, rectangular office tower, minimal facade",
    },
    {
        "id": "brutalism",
        "name": "Brutalizam",
        "period": "1950-e - 1970-e",
        "regions": ["Europa", "SAD", "bivša Jugoslavija", "svijet"],
        "materials": ["sirovi beton", "armirani beton", "staklo"],
        "features": ["masivni betonski volumeni", "vidljiva konstrukcija", "gruba tekstura", "monumentalnost", "oštri oblici"],
        "prompt": "Brutalist architecture, massive raw concrete volumes, rough texture, exposed structure, monumental geometric building",
    },
    {
        "id": "postmodernism",
        "name": "Postmodernizam",
        "period": "1970-e - 1990-e",
        "regions": ["SAD", "Europa", "svijet"],
        "materials": ["beton", "staklo", "kamen", "obojene fasade"],
        "features": ["povijesne reference", "igriva fasada", "boje", "simbolički elementi", "mješavina stilova"],
        "prompt": "Postmodern architecture, playful facade, historical references, colorful details, mixed forms, symbolic elements",
    },
    {
        "id": "high_tech",
        "name": "High-tech arhitektura",
        "period": "1970-e - danas",
        "regions": ["Europa", "SAD", "Japan", "svijet"],
        "materials": ["čelik", "staklo", "aluminij", "industrijski elementi"],
        "features": ["vidljive instalacije", "metalna konstrukcija", "staklene opne", "industrijski izgled", "tehnološki izraz"],
        "prompt": "High-tech architecture, exposed steel structure, glass skin, visible services, industrial technology aesthetic",
    },
    {
        "id": "deconstructivism",
        "name": "Dekonstruktivizam",
        "period": "1980-e - danas",
        "regions": ["Europa", "SAD", "svijet"],
        "materials": ["metal", "staklo", "beton", "titanij"],
        "features": ["fragmentirani oblici", "nagnute plohe", "dinamična geometrija", "nepravilni volumeni", "dramatičnost"],
        "prompt": "Deconstructivist architecture, fragmented forms, tilted planes, dynamic geometry, irregular metal and glass building",
    },
    {
        "id": "contemporary",
        "name": "Suvremena arhitektura",
        "period": "1990-e - danas",
        "regions": ["svijet"],
        "materials": ["staklo", "beton", "čelik", "drvo", "kompoziti"],
        "features": ["velike staklene stijene", "jednostavni volumeni", "održivi elementi", "otvoreni prostori", "minimalizam"],
        "prompt": "Contemporary architecture, clean volumes, large glass surfaces, concrete and wood, sustainable modern design",
    },
    {
        "id": "minimalism",
        "name": "Minimalizam",
        "period": "1960-e - danas",
        "regions": ["svijet"],
        "materials": ["beton", "staklo", "drvo", "bijele plohe"],
        "features": ["vrlo malo detalja", "čiste plohe", "jednostavni volumeni", "neutralne boje", "skriveni spojevi"],
        "prompt": "Minimalist architecture, simple geometric volumes, clean white surfaces, minimal details, calm modern facade",
    },
    {
        "id": "organic",
        "name": "Organska arhitektura",
        "period": "20. stoljeće - danas",
        "regions": ["SAD", "Europa", "svijet"],
        "materials": ["drvo", "kamen", "beton", "staklo"],
        "features": ["spajanje s prirodom", "prirodni materijali", "horizontalne linije", "nepravilni oblici", "terase"],
        "prompt": "Organic architecture, building integrated with nature, natural materials, stone and wood, flowing forms, terraces",
    },
    {
        "id": "vernacular",
        "name": "Vernakularna arhitektura",
        "period": "tradicionalno - danas",
        "regions": ["lokalne regije svijeta"],
        "materials": ["lokalni kamen", "drvo", "glina", "slama", "opeka"],
        "features": ["lokalni materijali", "prilagodba klimi", "jednostavna konstrukcija", "tradicijski detalji", "regionalni oblik"],
        "prompt": "Vernacular architecture, local materials, traditional regional building, climate adapted form, simple construction",
    },
    {
        "id": "mediterranean",
        "name": "Mediteranska arhitektura",
        "period": "tradicionalno - danas",
        "regions": ["Mediteran", "Dalmacija", "Italija", "Španjolska", "Grčka"],
        "materials": ["kamen", "žbuka", "terakota", "drvo"],
        "features": ["kamena fasada", "crijep", "lukovi", "skure", "bijele ili svijetle fasade", "terase"],
        "prompt": "Mediterranean architecture, stone walls, terracotta roof tiles, arches, shutters, light stucco facade, coastal house",
    },
    {
        "id": "ottoman",
        "name": "Osmanska arhitektura",
        "period": "14. - početak 20. stoljeća",
        "regions": ["Turska", "Balkan", "Bliski istok"],
        "materials": ["kamen", "opeka", "drvo", "olovo"],
        "features": ["džamija", "velike kupole", "minareti", "trijemovi", "dvorišta", "ritmični prozori", "vitki tornjevi"],
        "prompt": "Ottoman architecture, large central dome, slender minarets, arched courtyard, mosque complex, rhythmic windows",
    },
    {
        "id": "mughal",
        "name": "Mogulska arhitektura",
        "period": "16. - 18. stoljeće",
        "regions": ["Indija", "Pakistan", "Bangladeš"],
        "materials": ["bijeli mramor", "crveni pješčenjak", "intarzija", "kamen"],
        "features": ["lukovi", "velike kupole", "minareti", "simetrični vrtovi", "bogata kamena dekoracija"],
        "prompt": "Mughal architecture, white marble dome, red sandstone, symmetrical garden, minarets, ornate arched facade",
    },
    {
        "id": "chinese_traditional",
        "name": "Tradicionalna kineska arhitektura",
        "period": "tradicionalno - 20. stoljeće",
        "regions": ["Kina", "Istočna Azija"],
        "materials": ["drvo", "crijep", "kamen", "opeka"],
        "features": ["zakrivljeni krovovi", "drvene konstrukcije", "crveni stupovi", "dvorišta", "simetrija", "dekorativni krovni rubovi"],
        "prompt": "traditional Chinese architecture, curved tiled roof, wooden structure, red columns, courtyard, symmetrical layout",
    },
    {
        "id": "japanese_traditional",
        "name": "Tradicionalna japanska arhitektura",
        "period": "tradicionalno - danas",
        "regions": ["Japan"],
        "materials": ["drvo", "papir", "bambus", "crijep", "kamen"],
        "features": ["drvena konstrukcija", "klizna vrata", "duboki krovni prepusti", "tatami proporcije", "vrt", "jednostavnost"],
        "prompt": "traditional Japanese architecture, wooden structure, deep eaves, sliding doors, tatami proportions, garden, calm simplicity",
    },
    {
        "id": "prairie",
        "name": "Prairie stil",
        "period": "1900. - 1920-e",
        "regions": ["SAD"],
        "materials": ["opeka", "drvo", "žbuka", "kamen"],
        "features": ["horizontalne linije", "niski krovovi", "siroki prepusti", "trake prozora", "integracija s krajolikom"],
        "prompt": "Prairie style architecture, strong horizontal lines, low pitched roof, wide eaves, bands of windows, landscape integration",
    },
    {
        "id": "constructivism",
        "name": "Konstruktivizam",
        "period": "1920-e - 1930-e",
        "regions": ["Rusija", "Sovjetski Savez"],
        "materials": ["beton", "čelik", "staklo"],
        "features": ["dinamični volumeni", "industrijski izgled", "geometrija", "funkcionalnost", "avangardni oblici"],
        "prompt": "Constructivist architecture, dynamic geometric volumes, industrial materials, concrete and steel, avant-garde functional design",
    },
    {
        "id": "sustainable",
        "name": "Održiva / zelena arhitektura",
        "period": "1990-e - danas",
        "regions": ["svijet"],
        "materials": ["drvo", "reciklirani materijali", "staklo", "zelene fasade", "solarni paneli"],
        "features": ["zeleni krov", "solarni paneli", "prirodna ventilacija", "drvena konstrukcija", "energetska učinkovitost"],
        "prompt": "sustainable green architecture, green roof, solar panels, timber structure, natural ventilation, energy efficient facade",
    },
]


def get_style_prompts():
    # Promptovi koji se šalju modelu za prepoznavanje stilova
    return [style["prompt"] for style in ARCHITECTURE_STYLES]


def get_style_names():
    # Hrvatski nazivi stilova za prikaz u aplikaciji
    return [style["name"] for style in ARCHITECTURE_STYLES]


def get_style_by_id(style_id):
    # Dohvaćanje jednog stila prema ID-u
    for style in ARCHITECTURE_STYLES:
        if style["id"] == style_id:
            return style
    return None
